### ISSUE TITLE
Power consumption and safety

### ISSUE THREAD

**Issue by Patsjemoe** [mtnbkr88/ESP32CAMRemotePIR#3]
Hi,
Interesting article. 
1) have you measured power consumption of the total/how long does your battery lasts ? I have just started a similar project, and seems to drain the battery fast, even when putting esp32 in deep sleep. I suspect the dc dc , but need to check.
2) in your battery schematic, you bypass the dw01 protection ...why would you do that , you create a risk to blow up the battery..?
Thanks in advance
Regards
Ludo

**Comment by mtnbkr88** [comment]
Hi Ludo,

1. Yes, the DC-DC boost converter I use does have a 3mA draw when the PIR is in its monitoring mode and ESP32 is in deep sleep. My setup will go a few days with no sun before the battery runs out which has not been an issue since I always have lots of sun.

2. If the dw01 protection is in circuit, when I switch on the power the dw01 thinks there's an issue and it shuts off the output. Then I have to temporarily short the battery negative to the dw01 negative to make it work. I'm not willing to deal with that so I bypass the dw01. I'm not worried about blowing up the battery. Feel free to wire that part to include the dw01 protection in your circuit. Hopefully you'll have better luck with it starting correctly. It's possible that newer TP4056 boards have resolved the shutoff on power on issue.

My setup has been working fine for years. Thanks for your interest.

Ed

**Comment by Patsjemoe** [comment]
Hi Ed,
Thank you for your quick reply.
3 mA is a very good value, I had about 6 mA in deep sleep for esp32cam, but
saw that you also disable wifi...
Which DC DC do you use ? I am using MT3608, which is fine for quiescent
current, but I just noticed
 a strange behaviour with this device, it drops the output to 3.5 V when
starting esp32cam.  Current of 300mA should be well within the specs of the
MT3608 which is 2A.
The shutoff happens, but shorting as you mentioned starts up, but also,
when you power the TP4056, it also works fine.
best regards
Ludo

**Comment by mtnbkr88** [comment]
I used this one: https://www.ebay.com/itm/401149613381


-------- Original message --------
From: Patsjemoe ***@***.***>
Date: 10/28/22 1:53 AM (GMT-08:00)
To: mtnbkr88/ESP32CAMRemotePIR ***@***.***>
Cc: mtnbkr88 ***@***.***>, State change ***@***.***>
Subject: Re: [mtnbkr88/ESP32CAMRemotePIR] Power consumption and safety (Issue #3)


Hi Ed,
Thank you for your quick reply.
3 mA is a very good value, I had about 6 mA in deep sleep for esp32cam, but
saw that you also disable wifi...
Which DC DC do you use ? I am using MT3608, which is fine for quiescent
current, but I just noticed
a strange behaviour with this device, it drops the output to 3.5 V when
starting esp32cam. Current of 300mA should be well within the specs of the
MT3608 which is 2A.
The shutoff happens, but shorting as you mentioned starts up, but also,
when you power the TP4056, it also works fine.
best regards
Ludo
