### ISSUE TITLE
Re-wake up 

### ISSUE THREAD

**Issue by Patsjemoe** [mtnbkr88/ESP32CAMRemotePIR#6]
Hi Ed,
When setting  the daily  wake time to 6 seconds (save power) ,It makes a multiple wake up from 2 to 4 times. Any idea why that can be?
Regards
Ludo

**Comment by mtnbkr88** [comment]
Hi Ludo,
I'm not exactly sure what you mean by setting the daily wake time to 6 seconds. If you didn't change it the wake time is one specific time of day. The deep sleep logic calculates how long from current time to the daily wake time specified in your settings and uses that to set how long to sleep. If it wakes multiple times a day there is something wrong with the logic you are using to calculate how long to sleep.
Ed

**Comment by Patsjemoe** [comment]
Hi Ed,
It is the time it stays awake... 6 sec.
When it wakes up hasn't changed, 1x a day.
But it wakes up 2-4 times in a period of 1-2minutes, often it sends a photo
with the same wakeup time.
When setting time to 10 minutes, it is only once.... I wonder what triggers
this multiple wake up. Could you try yourself and see what happens?
Regards
Ludo

Op di 10 jan. 2023 22:00 schreef mtnbkr88 ***@***.***>:

**Comment by mtnbkr88** [comment]
If it fails to get a network connection it will sleep for a second and wake to try again. If it has trouble initializing the camera which happens often with mine it will retry again up to five times. If it thinks it failed to send the email it will retry sending the email multiple times. If you are using a PIR sensor that is too sensitive it can trigger often with false alarms. Mine goes crazy when it rains. Plus I don't know how you've modified the code. There are so many areas of possible trouble that I'm afraid there isn't one specific thing I can say is causing your issue.

Mine is normally sitting on a fence at the limits of my local wifi network. It's often having problems and when I bring it in and connect it to my laptop to watch the serial monitor it works better so I'm having difficulties with its inconsistent behavior. I'm still tweaking my code trying to make it work better but it never gets better. Unfortunately these little ESP32CAMs are not very reliable and probably should be considered as toys. It is what it is.

All I can suggest is to connect it to a serial port, put lots of Serial.println statements in areas you think might be where the problem is and watch the serial monitor for a while in hopes of capturing any clues to your issue.

Sorry I can't help more. 
Good Luck!

**Comment by Patsjemoe** [comment]
Hi Ed,
Thank you, so these retries are normal, depending the circumstance.....this
is clear. I also understand now where the 1 sec is used for... Was
wondering...

What I also observed... when the "10 min" server is active, I do not get
reaction to my PIR... Is this normal?

FYI  : I changed my esp32cam to take an external antenna, which I need, as
it also stands away from my house... This gives better results.

Thank you for your quick reply.

Regards
Ludo

Op wo 11 jan. 2023 08:47 schreef mtnbkr88 ***@***.***>:

**Comment by mtnbkr88** [comment]
Hi Ludo,

I put an up to 10 min wait for the PIR signal to stop when going to sleep to prevent continuous quick triggers. For me if too many emails are sent too quickly gmail locks my email account. I'm trying to prevent that. I'm sure you know you can change the code to do anything you want.

I've thought about adding an external antenna but I don't want to.

Ed
